"""new fields in user model

Revision ID: 901a774c1504
Revises: 4e67a9c43f95
Create Date: 2025-04-22 22:03:34.619657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901a774c1504'
down_revision = '4e67a9c43f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    with op.batch_alter_table('search', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_timestamp'))

    op.drop_table('search')
    # ### end Alembic commands ###
