"""add booksearch model

Revision ID: c951bfd7e148
Revises: 901a774c1504
Create Date: 2025-04-25 15:11:20.976845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c951bfd7e148'
down_revision = '901a774c1504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('authors', sa.String(length=256), nullable=True),
    sa.Column('thumbnail', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_date', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book_search', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_search_isbn'), ['isbn'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_search', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_search_isbn'))

    op.drop_table('book_search')
    # ### end Alembic commands ###
